#ifndef __BOOTLOADER_CONFIG_H
#define __BOOTLOADER_CONFIG_H

#define BOOTLOADER_SRAM_BASE_ADDR   0x20000000UL
#define BOOTLOADER_SRAM_SIZE        0x00020000UL
#define BOOTLOADER_SRAM_END_ADDR    (BOOTLOADER_SRAM_BASE_ADDR + BOOTLOADER_SRAM_SIZE)

#endif /* __BOOTLOADER_CONFIG_H */
